import{A as p,a as u,i as m,b as f}from"./assets/vendor-BxF25OBs.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();new p(".accordion-container");const r={menuBtn:document.querySelector(".header-btn-js"),menuList:document.querySelector(".menu-list-js"),openMenuBtn:document.querySelector("[data-menu-open]"),closeMenuBtn:document.querySelector("[data-menu-close]"),mobMenu:document.querySelector("[data-menu]"),menuLinks:document.querySelectorAll(".mob-menu-js a")};r.menuBtn.addEventListener("click",g);function g(){r.menuList.classList.toggle("active")}function d(){r.mobMenu.classList.toggle("is-open"),document.body.classList.toggle("no-scroll")}r.openMenuBtn.addEventListener("click",d);r.closeMenuBtn.addEventListener("click",d);r.menuLinks.forEach(t=>{t.addEventListener("click",()=>{r.mobMenu.classList.remove("is-open"),document.body.classList.remove("no-scroll")})});const h=u.create({baseURL:"https://portfolio-js.b.goit.study/api"}),a={reviewsListElem:document.querySelector(".reviews-list-js")};async function y(){try{return(await h.get("/reviews")).data}catch(t){return console.error("error geting reviews",t),m.error({title:"Error",message:"Not found",position:"topRight"}),null}}y().then(t=>{if(!t||t.length===0){a.reviewsListElem.innerHTML='<p class="error-message">Not found</p>';return}const s=L(t);a.reviewsListElem.innerHTML=s});function v(t){const{author:s,avatar_url:n,review:i}=t;return`<li class="reviews-list-item">
        <img class="reviews-list-img" src="${n}" alt="photo" />
        <h3 class="reviews-list-subtitle">${s}</h3>
        <p class="reviews-list-text">${i}</p>
      </li>`}function L(t){return t.map(v).join("")}const w={formElem:document.querySelector(".work-togethe-form")};w.formElem.addEventListener("submit",async t=>{t.preventDefault();const s=t.target,n=new FormData(s),i=n.get("email"),e=n.get("comment"),o={email:i,comment:e};try{if((await u.post("https://portfolio-js.b.goit.study/api/requests",o)).status===201){const l=f.create(`
                <div class="modal">
          <button class="modal-close"><svg class="menu-close-icon" width="34" height="34">
      <use href="/img/icons.svg#icon-close"></use>
    </svg></button>
          <h2 class="modal-title">Thank you for your interest in cooperation!</h2>
          <p class="modal-text">The manager will contact you shortly to discuss further details and opportunities for cooperation. Please stay in touch.</p>
        </div>
        `);l.show(),document.querySelector(".modal-close").addEventListener("click",()=>l.close()),s.reset()}}catch(c){m.error({title:"Error",message:"Failed to send request. Please check your input and try again.",position:"topRight"}),console.error("Form submission error:",c)}});
//# sourceMappingURL=index.js.map
